// frontend/src/app/pages/home/home.component.ts
import {AfterViewInit, Component, ElementRef, OnDestroy, OnInit, ViewChild} from '@angular/core';
import {Terminal} from "xterm";
import {FitAddon} from "xterm-addon-fit";
import {debounceTime, fromEvent, map, startWith, Subscription} from "rxjs";
import {Send} from "../../../wailsjs/go/service/MudService";
import {EventsOn, EventsEmit} from "../../../wailsjs/runtime";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements AfterViewInit, OnInit, OnDestroy {
  @ViewChild('term') terminalElement!: ElementRef;
  inputBuffer = "";
  terminal: Terminal | undefined;
  termFit: FitAddon | undefined;
  windowResizeSubs: Subscription | undefined;

  ngOnInit(): void {
    this.windowResizeSubs = windowSizeObserver().subscribe(({width, height}) => {
      this.termFit?.fit();
    })

    EventsOn("OnMessage", (message: string) => {
      this.terminal?.write(message);
    });
  }

  ngOnDestroy(): void {
    this.windowResizeSubs?.unsubscribe();
  }

  ngAfterViewInit(): void {
    // init terminal & addons
    this.terminal = new Terminal({
      allowProposedApi: true,
      fontFamily: "Gulimche",
      fontSize: 17,
    });
    this.termFit = new FitAddon();
    this.terminal.loadAddon(this.termFit);

    // open terminal in DOM
    this.terminal.open(this.terminalElement.nativeElement);
    setTimeout(() => {
      this.termFit?.fit();
    }, 1000);

    this.terminal.onData((data) => {
      this.terminal?.write(data);
    });

    EventsEmit("OnReady");
  }

  onKeyDown($event: KeyboardEvent) {
    if ($event.key === "Enter") {
      Send(this.inputBuffer);
      this.inputBuffer = "";
    }
  }
}

function windowSizeObserver(dTime = 300) {
  return fromEvent(window, 'resize').pipe(
    debounceTime(dTime),
    map(event => {
      const window = event.target as Window;
      return {width: window.innerWidth, height: window.innerHeight}
    }),
    startWith({width: window.innerWidth, height: window.innerHeight})
  );
}

<div class="flex flex-col h-full">
    <div class="output-layer" #term></div>
    <div class="w-full h-2 bg-gray-400"></div>
    <div class="input-layer">
        <input type="text" [(ngModel)]="inputBuffer"
               (keydown)="onKeyDown($event)"
               class="input input-bordered w-full bg-black h-20"
        />
    </div>
</div>

// frontend/src/routes/home/+page.svelte
<script lang="ts">
    import {onMount} from "svelte";
    import 'xterm/css/xterm.css';
    import {EventsEmit, EventsOn} from "$lib/wailsjs/runtime";
    import {Send} from "$lib/wailsjs/go/service/MudService";

    let terminalElement: HTMLElement;
    let isResizing = false;
    let terminal: any;
    let inputBuffer = "";

    async function initTerminal() {
        // import package dynamically
        const xterm = await import("xterm");
        const fit = await import("xterm-addon-fit");
        const webLinksAddon = await import("xterm-addon-web-links");

        // import classes
        const { Terminal } = xterm;
        const { FitAddon } = fit;
        const { WebLinksAddon } = webLinksAddon;

        // init terminal & addons
        terminal = new Terminal({allowProposedApi: true});
        const termFit = new FitAddon();
        terminal.loadAddon(new WebLinksAddon());
        terminal.loadAddon(termFit);

        // open terminal in DOM
        terminal.open(terminalElement);
        termFit.fit();

        // resize event handler
        window.addEventListener ("resize", (event: Event) => {
            if (isResizing)
                return;

            isResizing = true;
            setTimeout (() => {
                isResizing = false;
                termFit.fit();
            }, 500);
        });

        // paste (CMD-V) data
        terminal.onData((e) => {
            terminal.write(e);
        })

        // for (let i=0; i<100; i++) {
        //     terminal.write('Hello from \x1B[1;3;31mxterm.js\x1B[0m $ ')
        //     terminal.write("\n\r");
        // }
    }

    onMount(async () => {
        await initTerminal();
        EventsEmit("OnReady")
    });

    function onKeyPress (event:KeyboardEvent) {
        if (event.key === "Enter") {
            Send(inputBuffer);
            inputBuffer = "";
        }
    }

    EventsOn("OnMessage", (message: string) => {
       terminal.write(message);
    });
</script>

<svelte:head>
    <title>Home</title>
</svelte:head>

<div class="output-layer" bind:this={terminalElement}></div>
<div class="w-full h-2 bg-gray-400"></div>
<div class="input-layer">
    <input type="text"
           bind:value={inputBuffer}
           on:keypress={onKeyPress}
           class="input input-bordered w-full bg-black h-20"
    />
</div>

<style>
    .output-layer {
        @apply w-full;
        @apply h-full;
        @apply bg-black;
        @apply text-white;
        padding: 1rem 0 1rem 1rem;
    }

    .input-layer {
        @apply flex;
        @apply flex-col;
        @apply p-1.5;
        @apply w-full;
        @apply h-fit;
        background-color: #333;
        color: white;
        @apply overflow-auto;
        @apply rounded-none;
    }
</style>
